name: NodeJS with Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
    - name: Checkmarx AST Github Action
  # You may pin to the exact commit or the version.
  # uses: Checkmarx/ast-github-action@3bbaca0807ff5abd587965391138479c23b7b369
      uses: Checkmarx/ast-github-action@2.0.18
      with:
    # Provide the AST portal URL
         base_uri: https://deu.iam.checkmarx.net/
    # Provide the Tenant for AST portal URL
         cx_tenant: bhawani_singh_se
    # Client ID for AST portal authentication
         cx_client_id: GithubActions
    # Secret key for AST portal authentication
         cx_client_secret: 2YlhseVTbXfpVeFDhcoX1FlNXltHGdr2
